### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by alexanderGugel** [florianheinemann/passwordless-redisstore#6]
https://github.com/florianheinemann/passwordless-redisstore/blob/master/lib/redisstore.js#L11

Seems like this has been copied over.

**Comment by florianheinemann** [comment]
Fixed with https://github.com/florianheinemann/passwordless-redisstore/commit/8d684c7e188d781128e9686fe258cc807e2a3a7b and published as v1.0.1

Thanks!
