### ISSUE TITLE
Warning when using node_redis 2.5.3

### ISSUE THREAD

**Issue by stockholmux** [florianheinemann/passwordless-redisstore#8]
When using this module with [node_redis](https://github.com/NodeRedis/node_redis) 2.5.3, I'm getting the following notice:

```
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

I believe this is coming from `RedisStore.prototype.storeOrUpdate` and the argument `origin` is undefined.

**Comment by florianheinemann** [comment]
Hi! v1.0.2 that I just published should fix this issue. 
Thanks for making me aware!
